apiVersion: v2
name: my-istio
description: My Istio chart
version: 1.0.0
type: application
  #appVersion: "1.0.0"
dependencies:
  - name: base
    version: 1.16.1
    #repository: https://github.com/istio/istio/blob/master/manifests/charts/base
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.16.1
    #repository: https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery
    repository: https://istio-release.storage.googleapis.com/charts
