#
# Filename: Chart.yaml
# Description: A brief description of what this file contains
# Author: CloudifyOps
# Date: 2023-04-05
# Version: 1.0
# License: Copyright (c) [2023] CloudifyOps
#          This file is licensed under the CloudifyOps.

---
apiVersion: v2
type: application
name: secrets-store-csi-driver
version: 1.3.2
appVersion: 1.3.2
dependencies:
  - name: secrets-store-csi-driver
    repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    version: 1.3.2
