#
# Filename: Chart.yaml
# Description: A brief description of what this file contains
# Author: CloudifyOps
# Date: 2023-04-10
# Version: 1.0
# License: Copyright (c) [2023] CloudifyOps
#          This file is licensed under the CloudifyOps.
#

---
apiVersion: v1
type: application
name: node-problem-detector
version: 1.0.0
appVersion: v0.8.12
dependencies:
- name: node-problem-detector
  repository: https://charts.deliveryhero.io/  
  version: "2.3.4"
