# Filename: aws-load-balancer-controller.yaml
# Description: ArgoCD application file for aws-load-balancer-controller
# Author: CloudifyOps
# Date: YYYY-MM-DD
# Version: 1.0
# License: Copyright (c) [year] CloudifyOps
# This file is licensed under the CloudifyOps.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  aws-loadbalancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: gitops/argocd/helm/addons/aws-loadbalancer-controller
  labels: #change the names accordingly
    app.kubernetes.io/name: aws-loadbalancer-controller
    app.kubernetes.io/instance: aws-loadbalancer-controller-argocd-app
    app.kubernetes.io/component: aws-loadbalancer-controller
    app.kubernetes.io/part-of: aws-loadbalancer-controller
    
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc ## cluster URl
  project: default
  source:
    path: gitops/argocd/helm/addons/aws-loadbalancer-controller
    repoURL: https://github.com/devoptymize/devoptymize-k8ops.git
    targetRevision:  main
    helm:
      valueFiles:
        - values-aws.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - SkipDryRunOnMissingResource=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
