#
# Filename: aws-secrets-store-csi-driver-provider.yaml
# Description: ArgoCD application file for aws-secrets-store-csi-driver-provider
# Author: CloudifyOps
# Date: 2023-04-06
# Version: 1.0
# License: Copyright (c) [2023] CloudifyOps
#          This file is licensed under the CloudifyOps.
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver-provider-aws
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: gitops/argocd/helm/addons/aws-secret-store-csi-driver-provider

  labels: #change the names accordingly
    app.kubernetes.io/name: secrets-store-csi-driver-provider-aws
    app.kubernetes.io/instance: secrets-store-csi-driver-provider-aws-argocd-app
    app.kubernetes.io/component: csi-driver-provider
    app.kubernetes.io/part-of: secrets-store-csi-driver-provider-aws
spec:
  destination: 
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: gitops/argocd/helm/addons/aws-secret-store-csi-driver-provider
    repoURL: https://github.com/devoptymize/devoptymize-k8ops.git
    targetRevision: main
    helm:
      valueFiles: 
        - values-aws.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - SkipDryRunOnMissingResource=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    # retry:
    #   limit: 5
    #   backoff:
    #     duration: 5s
    #     factor: 2
    #     maxDuration: 3m0s
