#
# Filename: ebs-csi-driver.yaml
# Description: ArgoCD application file for ebs-csi-driver
# Author: CloudifyOps
# Date: 2023-04-06
# Version: 1.0
# License: Copyright (c) [2023] CloudifyOps
#          This file is licensed under the CloudifyOps.
#

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi-driver-aws
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: gitops/argocd/helm/addons/aws-ebs-csi-driver
  labels: #change the names accordingly
    app.kubernetes.io/name: ebs-csi-driver-aws
    app.kubernetes.io/instance: ebs-csi-driver-aws-argocd-app
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/part-of: ebs-csi-driver-aws
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/argocd/helm/addons/aws-ebs-csi-driver
    repoURL: https://github.com/devoptymize/devoptymize-k8ops.git
    targetRevision: main
    helm:
      valueFiles: 
        - values-aws.yaml 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - SkipDryRunOnMissingResource=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    # retry:
    #   limit: 5
    #   backoff:
    #     duration: 5s
    #     factor: 2
    #     maxDuration: 3m0s
