# Filename: velero.yaml
# Description: ArgoCD application file for velero
# Author: CloudifyOps
# Date: 2023-04-10
# Version: 1.0
# License: Copyright (c) [2023] CloudifyOps
# This file is licensed under the CloudifyOps.

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: gitops/argocd/helm/addons/velero
  labels: #change the names accordingly
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: velero-argocd-app
    app.kubernetes.io/component: velero
    app.kubernetes.io/part-of: velero

spec:
  destination:
    server: https://kubernetes.default.svc ## cluster url
    namespace: velero
  project: default
  source:
    path: gitops/argocd/helm/addons/velero
    repoURL: https://github.com/devoptymize/devoptymize-k8ops.git
    targetRevision:  main
    helm:
      valueFiles:
        - values-aws.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - SkipDryRunOnMissingResource=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
