# Filename: Chart.yaml
# Description: A brief description of what this file contains
# Author: CloudifyOps
# Date: 2023-04-10
# Version: 1.0
# License: Copyright (c) [2023] CloudifyOps
# This file is licensed under the CloudifyOps.

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: gitops/argocd/helm/secops/istio
  labels: #change the names accordingly
    app.kubernetes.io/name: istio
    app.kubernetes.io/instance: istio-argocd-app
    app.kubernetes.io/component: istio
    app.kubernetes.io/part-of: istio

spec:
  destination:
    server: https://kubernetes.default.svc ## cluster url
    namespace: istio-system
  project: default
  source:
    path: gitops/argocd/helm/secops/istio
    repoURL: https://github.com/devoptymize/devoptymize-k8ops.git
    targetRevision:  main
    helm:
      valueFiles:
        - values-aws.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - SkipDryRunOnMissingResource=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/failurePolicy
