#
# Filename: trivy-operator-argoapp.yaml
# Description: ArgoCD application file for trivy-operator
# Author: CloudifyOps
# Date: 2023-04-06
# Version: 1.0
# License: Copyright (c) [2023] CloudifyOps
#          This file is licensed under the CloudifyOps.
#

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#webhook-and-manifest-paths-annotation
    argocd.argoproj.io/manifest-generate-paths: gitops/argocd/helm/secops/trivy-operator
  labels:
    app.kubernetes.io/name: trivy-operator-aws
    app.kubernetes.io/instance: trivy-operator-aws-argocd-app
    app.kubernetes.io/component: secops
    app.kubernetes.io/part-of: trivy-operator-aws
spec:
  destination:
    namespace: secops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/argocd/helm/secops/trivy-operator
    repoURL: https://github.com/devoptymize/devoptymize-k8ops.git
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
      - values-aws-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - SkipDryRunOnMissingResource=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    # retry:
    #   limit: 5
    #   backoff:
    #     duration: 5s
    #     factor: 2
    #     maxDuration: 3m0s
